### PR TITLE
Welcome Back, a powerful Systemui tuner

### PR DESCRIPTION
**Pull request by aviraxp**
This will not cause issues, will it?

### CODE REVIEW

**Comment by aviraxp** [comment]
It is a simple revert of these two commits
https://github.com/android/platform_frameworks_base/commit/72195a011128d1c516149763c4c156539a470ed5
https://github.com/android/platform_frameworks_base/commit/52c66d74d13f26e2aea578f6f4308250cb958f67

**Comment by msfjarvis** [comment]
We still think your code is shit for no apparent reasons and will not merge
it even tho there's no actual code in there 😅

So... ¯_(ツ)_/¯

**Review by xdevs23 — COMMENTED** [review]
?

**Comment by aviraxp** [comment]
image

The systemui tuner will look like this (enable nav bar and color and appearance)

**Comment by xdevs23** [comment]
.... if you really want that.... let's reopen

**Comment by aviraxp** [comment]
OK, hunter finally enable it by https://github.com/halogenOS/android_frameworks_base/commit/79743715acd6e3a25f5ce829242336c4338a8d30.

**Pull request closed without merging**
