### PR TITLE
add DarkMode to nightmodefragment java

### PR DESCRIPTION
**Pull request by PaulSonOfLars**

### CODE REVIEW

**Comment by msfjarvis** [comment]
The commit that added the PreferenceSwitch for dark mode has been removed, sure you aren't going to raise an NPE with this?

**Comment by msfjarvis** [comment]
Lol, just saw the PR on settings repo. Ignore me

**Comment by PaulSonOfLars** [comment]
np, go ahead and double check everything! (hate git web)

**Comment by msfjarvis** [comment]
Nah, git web is good, you just need to make sure you know the stuff ;)

**Comment by PaulSonOfLars** [comment]
if GW was good, i would have been able to make a single PR :p

**Comment by msfjarvis** [comment]
One PR on two repos?

**Comment by PaulSonOfLars** [comment]
theres two PRs on this one

**Comment by msfjarvis** [comment]
Ahh yes, but it's still your fault lol, there are very easy ways to do it.
Fork the repo, make changes to the two files separately, THEN create a PR.
Would have only been one PR, and we could have squashed it into one commit
too, all online.

**Comment by PaulSonOfLars** [comment]
and now i know how to do it, so will do next time haha! cheers

**Review by xdevs23 — COMMENTED** [review]
Lgtm.
Needs test.

**Review by msfjarvis — APPROVED** [review]
Looks good to me. Merge approved.

**Comment by xdevs23** [comment]
> Looks good to me. Merge approved.

Needs test anyways

**Comment by msfjarvis** [comment]
Everything needs to be tested, no shit Sherlock

**Pull request merged**
